# Google Cloud Run service definition for Terraform Registry Frontend
# Deploy: gcloud run services replace frontend-service.yaml --region=REGION
#
# Prerequisites:
#   - Image pushed to Artifact Registry or GCR
#   - Backend service deployed and accessible

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: terraform-registry-frontend
  labels:
    app: terraform-registry
    component: frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containerConcurrency: 200
      timeoutSeconds: 60
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/terraform-registry/frontend:latest
          ports:
            - name: http1
              containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 30
