apiVersion: v2
name: terraform-registry
description: A Helm chart for deploying the Enterprise Terraform Registry
type: application
version: 1.1.10
appVersion: 1.1.10
keywords:
  - terraform
  - registry
  - infrastructure
  - devops
home: https://github.com/sethbacon/terraform-registry-backend
maintainers:
  - name: terraform-registry
