apiVersion: v2
name: terraform-registry
description: A Helm chart for deploying the Enterprise Terraform Registry
type: application
version: 2.5.1
appVersion: 2.5.1
keywords:
  - terraform
  - registry
  - infrastructure
  - devops
home: https://github.com/sethbacon/terraform-registry-backend
maintainers:
  - name: terraform-registry
