// Package auth provides authentication primitives (JWT, API keys) and the
// StateStore interface for OIDC session state management.
package auth

import (
	"context"
	"time"
)

// SessionState represents OAuth state during the authentication flow.
// It is stored temporarily between the login redirect and the callback.
type SessionState struct {
	State        string    `json:"state"`
	CreatedAt    time.Time `json:"created_at"`
	RedirectURL  string    `json:"redirect_url"`
	ProviderType string    `json:"provider_type"` // "oidc", "azuread", or "saml"
	// Nonce is the OIDC nonce generated by BeginAuth for this login attempt
	// (oidc and azuread providers only). It is persisted here and passed back
	// to VerifyIDToken via oidc.WithExpectedNonce at the callback, binding the
	// returned ID token to this specific login and defending against
	// injection/replay of a token issued for a different login attempt.
	Nonce string `json:"nonce,omitempty"`
	// CodeVerifier is the PKCE code verifier generated by BeginAuth for this
	// login attempt (oidc and azuread providers only). It is persisted here
	// and passed back to ExchangeCode via oidc.WithPKCEVerifier at the
	// callback, proving possession of the original authorization request and
	// defending against a stolen authorization code being redeemed elsewhere.
	CodeVerifier string `json:"code_verifier,omitempty"`
	// SAMLRequestID is the ID of the AuthnRequest issued for an SP-initiated
	// SAML login. It is echoed back by the IdP as InResponseTo and validated
	// at the ACS to bind the assertion to a request this SP actually made.
	SAMLRequestID string `json:"saml_request_id,omitempty"`
}

// StateStore is the interface for OIDC session state persistence.
// Implementations must be safe for concurrent use.
type StateStore interface {
	// Save persists a session state with the given TTL. After the TTL expires
	// the entry should be automatically removed.
	Save(ctx context.Context, state string, data *SessionState, ttl time.Duration) error
	// Load retrieves a previously saved session state. Returns nil, nil when
	// the key does not exist (expired or never saved).
	Load(ctx context.Context, state string) (*SessionState, error)
	// Delete removes a session state entry. Implementations should treat
	// deleting a non-existent key as a no-op.
	Delete(ctx context.Context, state string) error
	// Reserve atomically records a single-use marker under key for the given
	// TTL. It returns reserved=true when the key did not previously exist
	// (first use) and reserved=false when the key was already present, which
	// callers use to detect replays (e.g. an already-consumed SAML assertion
	// ID). Implementations must perform the check-and-set atomically.
	Reserve(ctx context.Context, key string, ttl time.Duration) (reserved bool, err error)
	// Close releases resources held by the store (stop goroutines, close connections).
	Close() error
}
