// Package docs embeds the generated OpenAPI/Swagger JSON specification and
// Swagger UI static assets into the server binary at compile time using Go's
// //go:embed directive. The spec is generated by swag from handler annotations
// and baked into the binary so that the registry is fully self-contained — no
// external spec file or CDN access is needed at runtime.
package docs

import (
	"embed"
	_ "embed"
)

// SwaggerJSON holds the raw bytes of the generated swagger.json OpenAPI spec.
//
//go:embed swagger.json
var SwaggerJSON []byte

// OpenAPI3JSON holds the raw bytes of openapi3.json — the same spec as
// SwaggerJSON converted from Swagger 2.0 to OpenAPI 3.0 via swagger2openapi.
// Downstream consumers (frontend typegen, provider oapi-codegen) want
// OpenAPI 3 natively; emitting both formats from this repo means each
// consumer doesn't have to run its own conversion step.
//
//go:embed openapi3.json
var OpenAPI3JSON []byte

// SwaggerUIAssets embeds the Swagger UI static files (JS bundle, standalone
// preset, CSS). These are served at /api-docs/static/ so the /api-docs/ page
// works in air-gapped environments without any CDN dependency.
//
//go:embed swagger-ui/*
var SwaggerUIAssets embed.FS
