// Package docs embeds the generated OpenAPI/Swagger JSON specification into
// the server binary at compile time using Go's //go:embed directive. The spec
// is generated by swag from handler annotations and baked into the binary so
// that the registry is fully self-contained — no external spec file needs to
// exist on the filesystem at runtime. Embedding is preferred over reading from
// disk because it eliminates a class of deployment failures where the spec file
// is missing, misplaced, or has incorrect permissions in the container image.
package docs

import _ "embed"

// SwaggerJSON holds the raw bytes of the generated swagger.json OpenAPI spec.
//
//go:embed swagger.json
var SwaggerJSON []byte
