// Package docs embeds the generated OpenAPI/Swagger JSON specification and
// Swagger UI static assets into the server binary at compile time using Go's
// //go:embed directive. The spec is generated by swag from handler annotations
// and baked into the binary so that the registry is fully self-contained — no
// external spec file or CDN access is needed at runtime.
package docs

import (
	"embed"
	_ "embed"
)

// SwaggerJSON holds the raw bytes of the generated swagger.json OpenAPI spec.
//
//go:embed swagger.json
var SwaggerJSON []byte

// SwaggerUIAssets embeds the Swagger UI static files (JS bundle, standalone
// preset, CSS). These are served at /api-docs/static/ so the /api-docs/ page
// works in air-gapped environments without any CDN dependency.
//
//go:embed swagger-ui/*
var SwaggerUIAssets embed.FS
